export const LOGIN = 'LOGIN';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
export const NEW_RELEASE_SONGS = 'NEW_RELEASE_SONGS';
export const FEATURED_PLAYLISTS = 'FEATURED_PLAYLISTS';
export const FEATURED_PLAYLISTS_SONGS = 'FEATURED_PLAYLISTS_SONGS';
export const USER_FEEDBACKS = 'USER_FEEDBACKS';
export const USER_DETAILS = 'USER_DETAILS';
export const SEARCH_SONGS = 'SEARCH_SONGS';

