name: Build and Push Docker Image to ECR
'on':
  push:
    branches:
      - main
jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build and push backend Docker image
        run: |
          docker build -t spotify-backend -f dockerfile --target backend .
          docker tag spotify-backend ${secrets.AWS_ACCOUNT_ID}.dkr.ecr.${secrets.AWS_REGION}.amazonaws.com/${secrets.ECR_REPO_NAME}:server
          docker push ${secrets.AWS_ACCOUNT_ID}.dkr.ecr.${secrets.AWS_REGION}.amazonaws.com/${secrets.ECR_REPO_NAME}:server
      - name: Build and push frontend Docker image
        run: |
          docker build -t spotify-frontend -f dockerfile --target frontend .
          docker tag spotify-frontend ${secrets.AWS_ACCOUNT_ID}.dkr.ecr.${secrets.AWS_REGION}.amazonaws.com/${secrets.ECR_REPO_NAME}:frontend
          docker push ${secrets.AWS_ACCOUNT_ID}.dkr.ecr.${secrets.AWS_REGION}.amazonaws.com/${secrets.ECR_REPO_NAME}:frontend
